# Discrete Kalman Filter

In [1]:
import numpy as np
import pandas as pd
from scipy.linalg import expm

### Helper Functions

In [2]:
def predictStep(x, A):
    xPred = np.matmul(A,x)
    return xPred

In [29]:
def innovationStep(xPred,z, H):
    innovation = np.subtract(z, np.matmul(H, xPred)) #innovation
    return innovation

In [42]:
def UpdateStep(xPred, nu, K):
    xNew = np.add(xPred, np.matmul(K, innovation))
    return xNew

In [6]:
def dataAssociation(xPred, rThetaMeasurement):
    pass

In [31]:
#initialize variables
deltaT = 50*10**-3 #50ms

#system matrix
A = np.array([
    [1, deltaT, 0,0],
    [0,1,0,0],
    [0,0,1,deltaT],
    [0,0,0,1]
])
#state transition matrix
F = expm(A*deltaT)
#output matrix
H = np.array([[1,0,0,0],
              [0,0,1,0]])
#covariance matrices
Q = np.eye(4)
R = np.ones(2).reshape(-1,1)
Pc = np.eye(4)

Ppred = np.add(np.matmul(np.matmul(A,Pc), np.transpose(A)), Q) #prediction covariance
S = np.add(R, np.matmul(np.matmul(H, Pd), np.transpose(H))) #innovation covariance
K = np.matmul(Pd, np.matmul(np.transpose(H), np.linalg.inv(S))) #kalman gain
Pupdate = np.subtract(Ppred, np.matmul(np.matmul(K, S), np.transpose(K))) #update covariance

In [21]:
#load in centroid data
#centroids are loaded in as a pandas dataframe (cartesianMeasurementCentroidDf)
#Header
# CentroidNumber | X | Y


In [9]:
#convert x,y to r,theta
measurementR = np.sqrt(np.square(cartesianMeasurementCentroidDf['X']) + np.square(cartesianMeasurementCentroidDf['Y']))
measurementTheta = np.arctan(cartesianMeasurementCentroidDf['Y']/cartesianMeasurementCentroidDf['X'])
polarCentroidDf = pd.DataFrame({'CentroidNumber':cartesianMeasurementCentroidDf['CentroidNumber'], 
                               'R': measurementR,
                               'Theta': measurementTheta})


### Unit Testing

In [32]:
#test predict step
x = np.expand_dims(np.array([1,0.5,0,0]), axis=1) #previous state
xPred = predictStep(x, A) #predicted state
xPred

array([[1.025],
       [0.5  ],
       [0.   ],
       [0.   ]])

In [35]:
#test innovation
#use xPred from previous step
# innovation(xPred, Pd, z, H, R)
z = np.expand_dims(np.array([1,0.5]), axis=1) #create column vector
innovation = innovationStep(xPred, z, H)
innovation

array([[-0.025],
       [ 0.5  ]])

In [43]:
#test update step
xNew = UpdateStep(xPred, innovation, K)
xNew

array([[0.88132417],
       [0.49641259],
       [0.38132417],
       [0.0095212 ]])