In [1]:
import serial
import time
import numpy as np

#pyqtgraph -> fast plotting
import pyqtgraph as pg
from pyqtgraph.Qt import QtGui

#matplotlib -> normal plotting
import matplotlib.pyplot as plt
%matplotlib inline

import copy

In [2]:
# Change the configuration file name
configFileName = 'mmw_pplcount_demo_default.cfg'

global CLIport
global Dataport

CLIport = {}
Dataport = {}

CLIport = serial.Serial('COM4', 115200)
if not(CLIport.is_open):
    CLIport.open()
Dataport = serial.Serial('COM3', 921600)
if not(Dataport.is_open):
    Dataport.open()

In [3]:
# Read the configuration file and send it to the board
config = [line.rstrip('\r\n') for line in open(configFileName)]
for i in config:
    CLIport.write((i+'\n').encode())
    print(i)
    time.sleep(0.01)

#close control port
CLIport.close()

dfeDataOutputMode 1
channelCfg 15 3 0
adcCfg 2 1
adcbufCfg 0 1 1 1 
profileCfg 0 77 30 7 62 0 0 60 1 128 2500 0 0 30
chirpCfg 0 0 0 0 0 0 0 1
chirpCfg 1 1 0 0 0 0 0 2
frameCfg 0 1 128 0 50 1 0
lowPower 0 1
guiMonitor 1 1 0 0
cfarCfg 6 4 4 4 4 16 16 4 4 50 62 0
doaCfg 600 1875 30 1
SceneryParam -6 6 0.05 6
GatingParam 4 3 2 0
StateParam 10 5 10 100 5
AllocationParam 450 0.01 25 1 2
VariationParam 0.289 0.289 1.0
PointCloudEn 1
trackingCfg 1 2 250 20 200 50 90
sensorStart


In [4]:
#initialise variables
lostSync = False

#valid header variables and constant
magicBytes = np.array([2,1,4,3,6,5,8,7], dtype= 'uint8')

isMagicOk = False
isDataOk = False
gotHeader = False

frameHeaderLength = 52 #52 bytes long
tlvHeaderLengthInBytes = 8
pointLengthInBytes = 16
frameNumber = 1
targetFrameNumber = 0



In [5]:
def validateChecksum(recieveHeader):
    uint32Convertor = [1, 2**8, 2**16, 2**24]
    uint16Convertor = uint32Convertor[0:2]
    h = np.uint16(recieveHeader)
    a = np.uint32(sum(h))
    b = np.uint16(a)
    CS = np.uint16(~(b))
    return CS

In [6]:
def readHeader(recieveHeader):
    headerContent = dict()
    index = 0
    
    headerContent['magicBytes'] = recieveHeader[index:index+8]
    index += 20
    
    headerContent['packetLength'] = recieveHeader[index:index+4].view(dtype=np.uint32)
    index += 4
        
    headerContent['frameNumber'] = recieveHeader[index:index+4].view(dtype=np.uint32)
    index += 24
    
    headerContent['numTLVs'] = recieveHeader[index:index+2].view(dtype=np.uint16)
    
    return headerContent

In [7]:
def tlvParsing(data, dataLength, tlvHeaderLengthInBytes, pointLengthInBytes):
    
    
    index = 0
    #tlv header parsing
    tlvType = data[index:index+4].view(dtype=np.uint32)
    tlvLength = data[index+4:index+8].view(dtype=np.uint32)
    
    #TLV size check
    if (tlvLength + index > dataLength):
        print('TLV SIZE IS WRONG')
        lostSync = True
        return
    
    index += tlvHeaderLengthInBytes
    tlvDataLength = tlvLength - tlvHeaderLengthInBytes
    if tlvType == 6: #point cloud TLV
        numberOfPoints = tlvDataLength/pointLengthInBytes
        print('NUMBER OF POINTS ', str(int(numberOfPoints)))
        if numberOfPoints > 0:
            p = data[index:index+tlvDataLength[0]].view(dtype=np.single)
            #form the appropriate array 
            #each point is 16 bytes - 4 bytes for each property - range, azimuth, doppler, snr
            pointCloud = np.reshape(p,(4, int(numberOfPoints)))
            return pointCloud
        
    

In [ ]:
#read and parse data

while Dataport.is_open:
    
    while (not(lostSync) and Dataport.is_open):
        #check for a valid frame header
        if not(gotHeader):
            
            #in_waiting = amount of bytes in the buffer
            rawRecieveHeader = Dataport.read(frameHeaderLength)
            recieveHeader = np.frombuffer(rawRecieveHeader, dtype = 'uint8')
            
        #magic byte check
        if not(np.array_equal(recieveHeader[0:8],magicBytes)):
            print('NO SYNC PATTERN')
            lostSync = True
            break

        #valid the checksum
#         CS = validateChecksum(recieveHeader)
        
        #have a valid frame header
        headerContent = readHeader(recieveHeader)
        print(headerContent)
        
        if (gotHeader):
            if headerContent['frameNumber'] > targetFrameNumber:
                targetFrameNumber = headerContent['frameNumber']
                gotHeader = False
                print('FOUND SYNC AT FRAME NUMBER ' + str(targetFrameNumber))
            else:
                print('OLD FRAME')
                gotHeader = False
                lostSync = True
                break
                
        dataLength = int(headerContent['packetLength'] - frameHeaderLength)
        if dataLength > 0:
            #read the rest of the packet
            rawData = Dataport.read(dataLength)
            data = np.frombuffer(rawData, dtype = 'uint8')
            pointCloud = tlvParsing(data, dataLength, tlvHeaderLengthInBytes, pointLengthInBytes)
            
            plt.tile
            
            
            
            

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([21842], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([21843], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([21844], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([21845], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([21846], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLe

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([21888], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([21889], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([21890], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([92], dtype=uint32), 'frameNumber': array([21891], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  2
[[ 1.3680205   0.45814893]
 [-0.08109608 12.91205   ]
 [ 1.3680205   0.425424  ]
 [ 0.08109608 15.793256  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([2

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([92], dtype=uint32), 'frameNumber': array([21927], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  2
[[ 1.3680205   0.45814893]
 [ 0.08109608 14.229745  ]
 [ 1.3680205   0.425424  ]
 [ 0.08109608 13.874541  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([21928], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([21929], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([21930], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([2

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([21964], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([92], dtype=uint32), 'frameNumber': array([21965], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  2
[[ 0.29314727  0.7853982 ]
 [-0.08109608  6.441597  ]
 [ 0.29314727  0.7526732 ]
 [-0.08109608  6.3566213 ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([92], dtype=uint32), 'frameNumber': array([21966], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  2
[[0.29314727 0.7853982 ]
 [0.08109608 6.450336  ]
 [0.29314727 0.7526732 ]
 [0.08109608 6.000331  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([108], dtype=uint32), 'frameNumber': array([21967], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBE

NUMBER OF POINTS  3
[[ 0.24428937  0.7853982  -0.08109608]
 [ 5.0680804   0.29314727  0.7853982 ]
 [ 0.16219215  6.8870006   0.29314727]
 [ 0.7526732   4.054804    6.3398614 ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([76], dtype=uint32), 'frameNumber': array([21992], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  1
[[1.4168783 ]
 [0.2945243 ]
 [0.08109608]
 [8.67554   ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([21993], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([21994], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([21995], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'

NUMBER OF POINTS  7
[[ 0.29314727  0.7853982   0.08109608  5.225768    0.29314727  0.7526732
  -0.08109608]
 [ 6.1011224   1.3680205   0.49087384 -0.16219215 22.573723    1.3680205
   0.45814893]
 [-0.16219215 31.802399    1.3680205   0.425424   -0.16219215 32.961914
   1.3680205 ]
 [ 0.3926991  -0.16219215 21.307611    1.3680205   0.35997415 -0.16219215
  12.304531  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([108], dtype=uint32), 'frameNumber': array([22021], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  3
[[ 0.29314727  0.7526732  -0.08109608]
 [ 5.0451975   1.3191626   0.5235988 ]
 [-0.08109608 13.839264    1.3680205 ]
 [ 0.49087384 -0.16219215 15.908758  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([140], dtype=uint32), 'frameNumber': array([22022], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  5
[[ 1.3191626   0.5235988  -0.08109608 24.044298    1.319

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([92], dtype=uint32), 'frameNumber': array([22046], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  2
[[ 1.3191626   0.5235988 ]
 [ 0.08109608 19.242636  ]
 [ 1.3191626   0.49087384]
 [ 0.08109608 29.8189    ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([92], dtype=uint32), 'frameNumber': array([22047], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  2
[[ 1.3191626   0.49087384]
 [-0.08109608 12.13977   ]
 [ 1.3191626   0.45814893]
 [-0.08109608 12.624329  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22048], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([76], dtype=uint32), 'frameNumber': array([22049], dtype=uint32), 'numTLVs': array([1], dtype=uint16)

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([124], dtype=uint32), 'frameNumber': array([22076], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  4
[[ 1.4168783   0.3926991  -0.08109608 15.173505  ]
 [ 1.3680205   0.35997415  0.08109608 10.664198  ]
 [ 1.4168783   0.35997415  0.08109608 23.136969  ]
 [ 1.4168783   0.32724923  0.72986466 15.13315   ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22077], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([124], dtype=uint32), 'frameNumber': array([22078], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  4
[[ 1.3680205   0.49087384 -0.08109608 15.808913  ]
 [ 1.3680205   0.45814893  0.08109608 14.41099   ]
 [ 1.4168783   0.32724923  0.08109608 11.57762   ]
 [ 1.4168783   0.2945243  -0.08109608 14.1

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22113], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22114], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22115], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22116], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22117], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLe

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22151], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22152], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22153], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22154], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22155], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLe

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22197], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([108], dtype=uint32), 'frameNumber': array([22198], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  3
[[ 1.4168783   0.32724923  0.08109608]
 [14.025608    1.4168783   0.2945243 ]
 [-0.08109608 19.589048    1.4168783 ]
 [ 0.2617994  -0.08109608 14.34075   ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([156], dtype=uint32), 'frameNumber': array([22199], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  6
[[ 1.0260154   0.88357294  0.08109608  5.437932    1.0260154   0.850848  ]
 [ 0.08109608  6.297061    1.4168783   0.3926991   0.08109608 33.717197  ]
 [ 1.4168783   0.35997415  0.08109608 39.349445    1.4168783   0.32724923]
 [-0.08109608 33.7

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22217], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([76], dtype=uint32), 'frameNumber': array([22218], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  1
[[ 1.4657363 ]
 [ 0.22907446]
 [-0.08109608]
 [ 9.763356  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22219], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22220], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22221], dtype=uint32), 'numTLVs': array([0], dtyp

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22257], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22258], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22259], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22260], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22261], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLe

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22302], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22303], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22304], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22305], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22306], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLe

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22347], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([76], dtype=uint32), 'frameNumber': array([22348], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  1
[[ 1.3191626 ]
 [ 0.06544985]
 [-0.08109608]
 [10.255822  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([76], dtype=uint32), 'frameNumber': array([22349], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  1
[[ 1.3191626 ]
 [ 0.06544985]
 [-0.08109608]
 [11.225297  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([92], dtype=uint32), 'frameNumber': array([22350], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  2
[[ 1.3191626   0.06544985]
 [-0.08109608 12.491272  ]
 [ 1.3680205   0.065

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22372], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([124], dtype=uint32), 'frameNumber': array([22373], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  4
[[ 1.3191626   0.425424   -0.08109608 11.830411  ]
 [ 1.3680205   0.3926991  -0.08109608 18.258434  ]
 [ 1.3680205   0.35997415 -0.08109608 20.000385  ]
 [ 1.3680205   0.32724923 -0.16219215 17.001274  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([92], dtype=uint32), 'frameNumber': array([22374], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  2
[[ 1.3680205   0.425424  ]
 [ 0.08109608 38.431835  ]
 [ 1.3680205   0.3926991 ]
 [ 0.08109608 32.698845  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([108

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22407], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22408], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22409], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22410], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22411], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLe

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([92], dtype=uint32), 'frameNumber': array([22442], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  2
[[ 1.3191626   0.06544985]
 [-0.08109608 16.998417  ]
 [ 1.3680205   0.06544985]
 [ 0.08109608 12.696866  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([124], dtype=uint32), 'frameNumber': array([22443], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  4
[[ 1.4657363   0.5235988   0.08109608 14.194955  ]
 [ 1.4657363   0.49087384  0.08109608 12.537076  ]
 [ 1.3191626   0.06544985 -0.16219215 25.931004  ]
 [ 1.3680205   0.06544985  0.08109608 10.440789  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([76], dtype=uint32), 'frameNumber': array([22444], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  1
[[ 1.3191626 ]
 [ 0.06544985]
 [ 0.08109608]
 [14.8814535 ]]
{'magi

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22482], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22483], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22484], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22485], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([92], dtype=uint32), 'frameNumber': array([22486], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  2
[[ 1.3680205   0.45814893]
 [-0.08109608 14.028897

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22527], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22528], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22529], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22530], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22531], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLe

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22567], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([140], dtype=uint32), 'frameNumber': array([22568], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  5
[[ 1.3680205   0.425424   -0.08109608 31.18633     1.4168783 ]
 [ 0.425424   -0.08109608 13.380657    1.3680205   0.3926991 ]
 [-0.08109608 25.676434    1.4168783   0.3926991  -0.08109608]
 [17.636244    1.4168783   0.35997415 -0.08109608 11.75923   ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22569], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22570], dtype=uint32), 'numTLVs': array([0

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22602], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22603], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22604], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([156], dtype=uint32), 'frameNumber': array([22605], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  6
[[ 0.29314727  0.7853982  -0.08109608  5.7641163   0.29314727  0.7526732 ]
 [-0.08109608  6.199557    1.3680205   0.5235988  -0.08109608 11.908324  ]
 [ 1.4168783   0.5235988  -0.08109608 12.612792    1.4168783   0.49087384]
 [-0.08109

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([92], dtype=uint32), 'frameNumber': array([22637], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  2
[[ 0.29314727  0.7853982 ]
 [-0.08109608  8.078066  ]
 [ 0.29314727  0.7526732 ]
 [-0.08109608  9.023622  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([92], dtype=uint32), 'frameNumber': array([22638], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  2
[[ 0.29314727  0.7853982 ]
 [-0.08109608  5.3207164 ]
 [ 0.29314727  0.7526732 ]
 [-0.08109608  5.3469467 ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([124], dtype=uint32), 'frameNumber': array([22639], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  4
[[ 0.24428937  0.8181231  -2.5139782   6.9384785 ]
 [ 0.24428937  0.7853982   4.946861    7.674296  ]
 [ 0.29314727  0.7853982  -0.08109608 10.656086  ]
 [ 0.29314

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22678], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22679], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22680], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22681], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22682], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLe

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22722], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([76], dtype=uint32), 'frameNumber': array([22723], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
NUMBER OF POINTS  1
[[ 1.2214469 ]
 [ 0.49087384]
 [ 0.08109608]
 [12.525153  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22724], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22725], dtype=uint32), 'numTLVs': array([0], dtype=uint16)}
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([52], dtype=uint32), 'frameNumber': array([22726], dtype=uint32), 'numTLVs': array([0], dtyp

NUMBER OF POINTS  13
[[  0.1954315    0.94902277   0.16219215 141.50647      0.24428937
    0.94902277   0.3243843   44.422028     0.34200513   0.94902277
    0.40548038   9.54417      0.1954315 ]
 [  0.91629785   0.16219215 138.60336      0.24428937   0.91629785
    0.24328822  42.018723     0.34200513   0.91629785   0.40548038
   10.012251     0.1954315    0.88357294]
 [  0.16219215 129.28125      0.24428937   0.88357294   0.16219215
   37.590305     0.29314727   0.88357294   0.24328822  10.667096
    0.34200513   0.88357294   0.48657644]
 [ 10.036805     0.1954315    0.850848     0.16219215 110.43674
    0.29314727   0.850848     0.24328822  11.204253     0.34200513
    0.850848     0.56767255   9.384487  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([189], dtype=uint32), 'frameNumber': array([22740], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  2
[[ 0.48857874 -0.49087384]
 [ 0.16219215 24.212912  ]
 [ 0.48857874 -0.4

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([407], dtype=uint32), 'frameNumber': array([22751], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  15
[[ 1.4168783   0.49087384  0.08109608 19.395271    1.2703048   0.45814893
   0.16219215 15.220215    1.4168783   0.45814893  0.24328822 29.814169
   1.2703048   0.425424    0.24328822]
 [14.852381    1.4168783   0.425424    0.16219215 20.528835    0.68401027
   0.3926991   1.0542489   5.7810307   0.73286813  0.3926991   1.0542489
   8.594182    0.73286813  0.35997415]
 [ 1.0542489  10.0292425   0.48857874  0.32724923  0.40548038  8.454456
   0.9282996   0.32724923  0.40548038  7.1203246   0.48857874  0.2945243
   0.40548038  8.093436    0.9282996 ]
 [ 0.2945243   0.72986466 11.6758175   0.9282996   0.2617994   0.72986466
  11.152469    0.9771575   0.2617994   0.72986466  7.797803    0.9771575
   0.22907446  0.72986466  7.228147  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dty

NUMBER OF POINTS  29
[[ 1.2214469   0.5235988  -0.08109608 19.593414    1.2214469   0.49087384
  -0.08109608 20.025633    1.4657363   0.45814893  0.24328822 15.305642
   1.563452    0.45814893  0.3243843  12.852989    1.1237311   0.425424
   0.8920568  15.411628    1.4657363   0.425424    0.24328822 16.616419
   1.5145941   0.425424    0.3243843  13.788257    1.563452  ]
 [ 0.425424    0.3243843  13.372458    1.1237311   0.3926991   0.8920568
  16.910347    1.1725891   0.3926991   0.81096077 37.65181     1.4657363
   0.3926991   0.3243843  16.730087    1.5145941   0.3926991   0.3243843
  16.844515    1.1237311   0.35997415  0.9731529  11.463847    1.1725891
   0.35997415  0.72986466 38.67601     1.2214469   0.35997415]
 [ 0.6487686  25.81771     1.4168783   0.35997415  0.16219215 19.635317
   1.4657363   0.35997415  0.3243843  16.402985    1.5145941   0.35997415
   0.3243843  15.91541     1.2214469   0.32724923  0.72986466 30.321947
   1.2703048   0.32724923  0.72986466 31.89924     1.

NUMBER OF POINTS  5
[[ 1.3680205   0.45814893  0.24328822 27.35227     1.3680205 ]
 [ 0.425424    0.24328822 36.308567    1.3680205   0.3926991 ]
 [ 0.08109608 35.56628     1.3680205   0.35997415  0.08109608]
 [26.566498    1.3680205   0.32724923  0.08109608 18.11079   ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([277], dtype=uint32), 'frameNumber': array([22768], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  8
[[ 1.4168783   0.49087384  0.24328822 11.501033    1.4168783   0.45814893
   0.24328822 13.052586  ]
 [ 1.3191626   0.3926991   0.08109608 24.063492    1.3191626   0.35997415
   0.08109608 24.474396  ]
 [ 1.3191626   0.32724923  0.08109608 15.086484    1.5145941   0.2617994
  -0.08109608 16.354448  ]
 [ 1.5145941   0.22907446 -0.08109608 16.254936    1.5145941   0.19634955
  -0.08109608 12.583301  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([392], dtype=uint32), 'frameNumbe

NUMBER OF POINTS  9
[[ 1.3680205   0.45814893 -0.16219215 23.848845    1.3680205   0.425424
  -0.08109608 32.56417     1.3191626 ]
 [ 0.3926991  -0.08109608 15.313461    1.3680205   0.3926991  -0.08109608
  23.650595    1.563452    0.3926991 ]
 [-0.08109608  9.652006    1.5145941   0.35997415 -0.08109608 19.489952
   1.563452    0.35997415 -0.08109608]
 [ 8.1904335   1.5145941   0.32724923 -0.08109608 29.109407    1.5145941
   0.2945243   0.08109608 14.175556  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([185], dtype=uint32), 'frameNumber': array([22789], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  2
[[ 1.6123099   0.35997415]
 [-0.08109608  7.659053  ]
 [ 1.6123099   0.32724923]
 [-0.08109608  7.3416653 ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([162], dtype=uint32), 'frameNumber': array([22790], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  1
[[ 1.6123

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([177], dtype=uint32), 'frameNumber': array([22821], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  2
[[ 1.4168783   0.5563237 ]
 [-0.08109608 21.171461  ]
 [ 1.4168783   0.5235988 ]
 [ 0.08109608 18.304846  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([138], dtype=uint32), 'frameNumber': array([22822], dtype=uint32), 'numTLVs': array([2], dtype=uint16)}
None
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([128], dtype=uint32), 'frameNumber': array([22823], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
None
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([128], dtype=uint32), 'frameNumber': array([22824], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
None
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([128], dtype=uint32), 'fr

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([188], dtype=uint32), 'frameNumber': array([22851], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  2
[[ 1.4168783   0.35997415]
 [ 0.08109608 12.31273   ]
 [ 1.1725891  -0.09817477]
 [-0.16219215 13.462716  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([386], dtype=uint32), 'frameNumber': array([22852], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  15
[[ 1.3680205   0.35997415  0.08109608 25.219574    1.4168783   0.35997415
   0.08109608 23.493183    1.4657363   0.35997415  0.08109608 12.923879
   1.5145941   0.35997415  0.16219215]
 [15.290372    1.3680205   0.32724923  0.08109608 22.47841     1.4168783
   0.32724923  0.08109608 36.944996    1.4657363   0.32724923  0.08109608
  18.38311     1.5145941   0.32724923]
 [ 0.16219215 21.677902    1.4168783   0.2945243   0.08109608 29.473639
   1.4657363   0.2945243   0.0810

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([352], dtype=uint32), 'frameNumber': array([22865], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  12
[[ 1.3680205   0.3926991   0.08109608 22.638792    1.3680205   0.35997415
   0.08109608 35.460587    1.3680205   0.32724923 -0.16219215 41.739693  ]
 [ 1.3191626   0.2945243  -0.16219215 12.729358    1.3680205   0.2945243
  -0.16219215 31.418896    1.4168783   0.2945243  -0.16219215 16.375826  ]
 [ 1.3680205   0.2617994  -0.08109608 19.008244    1.4168783   0.2617994
  -0.16219215 20.221075    1.4168783   0.22907446 -0.24328822 16.923542  ]
 [ 1.4168783   0.19634955 -0.08109608 11.1229105   1.5145941   0.19634955
  -0.16219215 11.5313225   1.5145941   0.16362461 -0.16219215 11.449428  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([364], dtype=uint32), 'frameNumber': array([22866], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF 

NUMBER OF POINTS  10
[[ 1.3191626e+00  3.2724923e-01 -1.6219215e-01  1.3318777e+02
   1.4168783e+00  3.2724923e-01 -8.1096075e-02  1.0097650e+01
   1.3191626e+00  2.9452431e-01]
 [-8.1096075e-02  2.0254008e+02  1.3680205e+00  2.9452431e-01
  -8.1096075e-02  3.0715948e+01  1.4168783e+00  2.9452431e-01
  -8.1096075e-02  1.4247582e+01]
 [ 1.3191626e+00  2.6179940e-01 -8.1096075e-02  1.4430919e+02
   1.3680205e+00  2.6179940e-01 -8.1096075e-02  3.3929214e+01
   1.4168783e+00  2.6179940e-01]
 [-8.1096075e-02  9.9179888e+00  1.3191626e+00  2.2907446e-01
   8.1096075e-02  7.5943588e+01  1.3680205e+00  2.2907446e-01
  -8.1096075e-02  3.1614006e+01]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([146], dtype=uint32), 'frameNumber': array([22875], dtype=uint32), 'numTLVs': array([2], dtype=uint16)}
None
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([184], dtype=uint32), 'frameNumber': array([22876], dtype=uint32), 'numTLVs

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([319], dtype=uint32), 'frameNumber': array([22891], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  10
[[ 1.3680205   0.3926991  -0.08109608 20.024843    1.4168783   0.3926991
  -0.08109608 12.501971    1.3680205   0.35997415]
 [ 0.08109608 24.978678    1.4168783   0.35997415 -0.08109608 12.545115
   1.3191626   0.32724923  0.16219215 12.876521  ]
 [ 1.3680205   0.32724923  0.08109608 28.068008    1.3191626   0.2945243
   0.16219215 11.970882    1.3680205   0.2945243 ]
 [ 0.08109608 26.938793    1.3680205   0.2617994   0.16219215 21.154667
   1.3680205   0.22907446  0.16219215 14.143137  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([538], dtype=uint32), 'frameNumber': array([22892], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  24
[[ 1.41687834e+00  4.25424010e-01 -8.10960755e-02  1.88009567e+01
   1.36802053e+00  3.92

None
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([200], dtype=uint32), 'frameNumber': array([22900], dtype=uint32), 'numTLVs': array([2], dtype=uint16)}
NUMBER OF POINTS  4
[[ 1.3680205   0.32724923  0.08109608 19.828648  ]
 [ 1.3680205   0.2945243   0.08109608 21.823069  ]
 [ 1.3680205   0.2617994   0.08109608 17.788387  ]
 [ 1.4657363   0.22907446  0.08109608  9.157449  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([324], dtype=uint32), 'frameNumber': array([22901], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  11
[[ 1.3191626   0.3926991  -0.08109608 17.653193    1.3191626   0.35997415
  -0.08109608 13.575131    1.3680205   0.35997415  0.08109608]
 [20.189613    1.3680205   0.32724923  0.08109608 33.992485    1.4168783
   0.32724923 -0.08109608 18.014933    1.3680205   0.2945243 ]
 [-0.08109608 27.125149    1.4168783   0.2945243  -0.08109608 25.957788
   1.4657363   0.2945243  -0.0

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([346], dtype=uint32), 'frameNumber': array([22915], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  12
[[ 1.6123099   0.45814893  0.08109608 10.341079    1.6123099   0.425424
   0.08109608 13.532462    1.3191626   0.3926991   0.08109608 27.183697  ]
 [ 1.3191626   0.35997415 -0.16219215 39.270412    1.3680205   0.35997415
  -0.08109608 40.71782     1.5145941   0.35997415  0.08109608  8.135975  ]
 [ 1.3191626   0.32724923 -0.16219215 36.91722     1.3680205   0.32724923
  -0.08109608 47.342636    1.5145941   0.32724923  0.08109608 10.119884  ]
 [ 1.3680205   0.2945243  -0.16219215 45.689857    1.5145941   0.2945243
   0.08109608  7.897418    1.3680205   0.2617994  -0.16219215 33.56311   ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([412], dtype=uint32), 'frameNumber': array([22916], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF P

NUMBER OF POINTS  18
[[ 1.4168783   0.62177354 -0.08109608 31.908928    1.4168783   0.5890486
  -0.08109608 61.51094     1.4168783   0.5563237  -0.08109608 77.99365
   1.4657363   0.5563237  -0.08109608 11.217479    1.4168783   0.5235988 ]
 [ 0.16219215 50.617638    1.3191626   0.45814893 -0.08109608 25.60325
   1.3680205   0.45814893  0.16219215 38.177048    1.3191626   0.425424
   0.08109608 30.110342    1.3680205   0.425424    0.16219215 49.374443  ]
 [ 1.3191626   0.3926991   0.24328822 27.326591    1.3680205   0.3926991
   0.08109608 43.611862    1.1237311   0.32724923  0.16219215 10.962667
   1.1725891   0.32724923  0.24328822 24.72098     1.1237311   0.2945243 ]
 [ 0.16219215 14.542639    1.1725891   0.2945243   0.24328822 27.771635
   1.1725891  -0.1308997   0.08109608 24.796356    1.1725891  -0.09817477
   0.08109608 58.62934     1.2703048  -0.09817477  0.3243843  13.824822  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([354], dtype=uint

NUMBER OF POINTS  29
[[ 1.3680205   0.45814893 -0.08109608 26.4606      1.4657363   0.45814893
  -0.08109608 21.589384    1.3680205   0.425424   -0.08109608 28.821934
   1.4657363   0.425424   -0.08109608 27.039774    1.5145941   0.425424
  -0.16219215 16.471472    1.3680205   0.3926991  -0.08109608 23.110668
   1.4657363   0.3926991  -0.08109608 29.775537    1.5145941 ]
 [ 0.3926991  -0.16219215 17.327019    1.4168783   0.35997415 -0.08109608
  23.107723    1.4657363   0.35997415 -0.08109608 31.599203    1.5145941
   0.35997415 -0.16219215 17.719616    1.4168783   0.32724923 -0.08109608
  28.789427    1.4657363   0.32724923 -0.08109608 34.719303    1.5145941
   0.32724923 -0.16219215 19.42891     1.563452    0.32724923]
 [ 0.08109608 13.188613    1.4168783   0.2945243  -0.08109608 37.957718
   1.4657363   0.2945243   0.08109608 38.33422     1.5145941   0.2945243
   0.08109608 23.729853    1.563452    0.2945243   0.08109608 14.987837
   1.4168783   0.2617994   0.08109608 44.6328      1

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([196], dtype=uint32), 'frameNumber': array([22947], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  3
[[ 1.5145941   0.35997415 -0.08109608]
 [17.566065    1.563452    0.35997415]
 [-0.08109608 12.56817     1.5145941 ]
 [-0.09817477  0.16219215 14.374959  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([195], dtype=uint32), 'frameNumber': array([22948], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  3
[[ 1.5145941   0.32724923  0.08109608]
 [25.488426    1.5145941   0.2945243 ]
 [-0.08109608 31.011759    1.5145941 ]
 [ 0.2617994  -0.08109608 20.825333  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([291], dtype=uint32), 'frameNumber': array([22949], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  9
[[ 1.3680205   0.425424   -0.08109608 15.935811    1.3680205   0.

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([163], dtype=uint32), 'frameNumber': array([22981], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  1
[[ 1.2703048 ]
 [ 0.06544985]
 [ 0.48657644]
 [13.873521  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([305], dtype=uint32), 'frameNumber': array([22982], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  10
[[ 1.6123099   0.35997415 -0.08109608  8.826126    1.3680205   0.19634955
  -0.16219215 15.063335    1.3680205   0.16362461]
 [-0.16219215 19.332047    1.2703048   0.1308997  -0.16219215 10.198113
   1.3680205   0.1308997  -0.16219215 19.341522  ]
 [ 1.2703048   0.09817477 -0.16219215 16.10569     1.3191626   0.09817477
  -0.16219215 12.993732    1.3680205   0.09817477]
 [ 0.56767255 13.105147    1.2703048   0.06544985  0.56767255 19.392351
   1.3191626   0.06544985  0.56767255 13.836921  ]]
{'magicBytes': array([2, 1,

NUMBER OF POINTS  27
[[ 1.2214469   0.425424   -0.8920568  34.413475    1.2703048   0.425424
  -0.72986466 16.40908     1.2214469   0.3926991  -0.81096077 53.412884
   1.2703048   0.3926991  -0.81096077 22.970552    1.2214469   0.35997415
  -0.6487686  35.199776    1.2703048   0.35997415 -0.6487686  24.013884
   1.3191626   0.35997415 -0.56767255]
 [19.08806     1.4168783   0.35997415 -0.8920568   9.748841    1.4657363
   0.35997415 -0.8920568  11.745562    1.5145941   0.35997415 -0.08109608
  18.045937    1.2703048   0.32724923 -0.6487686  18.723585    1.3191626
   0.32724923 -0.56767255 26.010199    1.4168783   0.32724923 -0.8920568
  10.944104    1.4657363   0.32724923]
 [-0.16219215 11.948872    1.5145941   0.32724923 -0.08109608 26.484478
   1.3191626   0.2945243  -0.56767255 32.601467    1.3680205   0.2945243
  -0.56767255 15.918131    1.4168783   0.2945243  -0.3243843  15.003807
   1.5145941   0.2945243  -0.08109608 20.641996    1.3191626   0.2617994
  -0.56767255 32.190178    1

NUMBER OF POINTS  19
[[ 1.4657363   0.49087384 -0.08109608 10.5258255   1.5145941   0.49087384
  -0.08109608 18.091887    1.4657363   0.45814893 -0.08109608 21.834572
   1.5145941   0.45814893 -0.08109608 25.422773    1.4168783   0.425424
  -0.16219215]
 [ 8.706548    1.4657363   0.425424   -0.16219215 20.040236    1.5145941
   0.425424   -0.16219215 14.879798    0.9771575   0.3926991  -0.3243843
   7.4274683   0.87944174  0.35997415 -0.16219215  9.444973    0.9282996
   0.35997415]
 [-0.16219215 10.257958    0.9771575   0.35997415 -0.3243843   7.942015
   0.87944174  0.32724923 -0.24328822  9.456463    0.9282996   0.32724923
  -0.24328822 13.302124    0.9771575   0.32724923 -0.3243843   6.964525
   0.87944174]
 [ 0.2945243  -0.24328822  7.698093    0.9282996   0.2945243  -0.24328822
  11.883097    1.1237311   0.2945243  -0.16219215  6.4383      0.9282996
   0.2617994  -0.24328822  8.229788    1.3680205   0.06544985 -0.08109608
   6.2944055 ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8,

NUMBER OF POINTS  1
[[ 2.1497464 ]
 [ 0.1308997 ]
 [-0.08109608]
 [ 6.147431  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([177], dtype=uint32), 'frameNumber': array([23020], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  2
[[ 2.2474623   0.22907446]
 [-0.08109608  6.3932877 ]
 [ 1.3191626   0.06544985]
 [ 0.08109608  8.372296  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([242], dtype=uint32), 'frameNumber': array([23021], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  6
[[ 1.5145941   0.45814893 -0.08109608 12.243911    1.2214469   0.425424  ]
 [ 0.72986466 15.238299    1.5145941   0.425424   -0.08109608 11.282367  ]
 [ 1.2214469   0.3926991   0.48657644 21.460463    1.2214469   0.35997415]
 [ 0.6487686  22.035118    1.2214469   0.32724923 -0.08109608 16.259111  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([230], dtype

NUMBER OF POINTS  14
[[ 1.4657363   0.49087384  0.24328822 12.330753    1.4657363   0.45814893
   0.24328822 15.622346    1.1725891   0.425424   -0.56767255 21.28156
   1.2214469   0.425424  ]
 [-0.56767255 21.03166     1.2703048   0.425424   -0.40548038 10.687068
   1.4657363   0.425424    0.24328822 12.963434    1.1237311   0.3926991
  -0.56767255 13.788913  ]
 [ 1.1725891   0.3926991  -0.56767255 20.986355    1.2214469   0.3926991
  -0.56767255 33.155178    1.2703048   0.3926991  -0.56767255 12.876665
   1.1237311   0.35997415]
 [-0.56767255 13.33575     1.2214469   0.35997415 -0.40548038 32.71223
   1.2703048   0.35997415 -0.56767255 11.61973     1.2214469   0.32724923
  -0.40548038 19.921139  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([206], dtype=uint32), 'frameNumber': array([23055], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  3
[[ 1.1725891   0.425424   -0.9731529 ]
 [20.509783    1.1725891   0.3926991 ]
 [-0.

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([278], dtype=uint32), 'frameNumber': array([23071], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  8
[[ 1.2214469   0.49087384  0.40548038 42.9397      1.2703048   0.49087384
   0.3243843  21.485794  ]
 [ 1.2214469   0.45814893  0.3243843  65.619995    1.2703048   0.45814893
   0.3243843  34.82698   ]
 [ 1.3191626   0.45814893  0.3243843  10.193203    1.2214469   0.425424
   0.3243843  50.020645  ]
 [ 1.2703048   0.425424    0.40548038 24.219437    1.3191626   0.425424
   0.3243843   9.562318  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([248], dtype=uint32), 'frameNumber': array([23072], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  6
[[ 1.2214469   0.49087384  0.3243843  18.219542    1.2214469   0.45814893]
 [ 0.24328822 24.489126    1.2703048   0.45814893  0.3243843  19.245226  ]
 [ 1.2214469   0.425424    0.243288

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([426], dtype=uint32), 'frameNumber': array([23101], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  17
[[ 1.3680205   0.49087384 -0.16219215 25.6983      1.3191626   0.45814893
  -0.08109608 14.922019    1.3680205   0.45814893 -0.08109608 28.43126
   1.3191626   0.425424   -0.08109608 16.833742    1.3680205 ]
 [ 0.425424   -0.08109608 19.778257    1.4168783   0.425424   -0.16219215
  17.864832    1.3191626   0.3926991  -0.08109608 13.3123255   1.4168783
   0.3926991   0.08109608 16.339262    1.4168783   0.35997415]
 [ 0.08109608 12.943069    1.2214469   0.2617994   0.08109608 15.643756
   1.2703048   0.2617994   0.08109608 17.73503     1.3680205   0.2617994
   0.08109608 12.14867     1.2214469   0.22907446  0.08109608]
 [19.969847    1.2703048   0.22907446  0.08109608 23.658012    1.3680205
   0.22907446  0.08109608 12.188883    1.2214469   0.19634955  0.08109608
  13.059762    1.27

NUMBER OF POINTS  4
[[ 1.4168783   0.35997415  0.08109608 20.029802  ]
 [ 1.4168783   0.32724923  0.08109608 34.601967  ]
 [ 1.4168783   0.2945243   0.08109608 34.7467    ]
 [ 1.4168783   0.2617994   0.08109608 15.726188  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([180], dtype=uint32), 'frameNumber': array([23119], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  2
[[ 1.4168783   0.32724923]
 [ 0.08109608 18.007313  ]
 [ 1.4168783   0.2945243 ]
 [ 0.08109608 18.01853   ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([178], dtype=uint32), 'frameNumber': array([23120], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  2
[[ 1.4168783   0.32724923]
 [ 0.08109608 15.339045  ]
 [ 1.4168783   0.2945243 ]
 [ 0.08109608 14.697967  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([210], dtype=uint32), 'frameNumber': array([23121], dtype=ui

None
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([128], dtype=uint32), 'frameNumber': array([23155], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
None
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([128], dtype=uint32), 'frameNumber': array([23156], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
None
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([128], dtype=uint32), 'frameNumber': array([23157], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
None
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([128], dtype=uint32), 'frameNumber': array([23158], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
None
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([128], dtype=uint32), 'frameNumber': array([23159], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
None
{'magicBytes': array([2, 1, 4, 3, 6

None
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([128], dtype=uint32), 'frameNumber': array([23185], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
None
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([128], dtype=uint32), 'frameNumber': array([23186], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
None
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([128], dtype=uint32), 'frameNumber': array([23187], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
None
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([152], dtype=uint32), 'frameNumber': array([23188], dtype=uint32), 'numTLVs': array([2], dtype=uint16)}
NUMBER OF POINTS  1
[[ 1.6123099 ]
 [ 0.06544985]
 [-0.08109608]
 [ 7.663565  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([137], dtype=uint32), 'frameNumber': array([23189], dtype=uint32), '

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([128], dtype=uint32), 'frameNumber': array([23228], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
None
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([184], dtype=uint32), 'frameNumber': array([23229], dtype=uint32), 'numTLVs': array([2], dtype=uint16)}
NUMBER OF POINTS  3
[[ 1.2703048  -0.35997415 -0.08109608]
 [14.073088    1.4657363   0.32724923]
 [-0.08109608 10.26057     1.2703048 ]
 [-0.32724923 -0.08109608 11.386156  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([227], dtype=uint32), 'frameNumber': array([23230], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  5
[[ 1.4168783   0.35997415 -0.08109608 15.401295    1.4657363 ]
 [ 0.35997415 -0.08109608 19.728077    1.4657363   0.32724923]
 [-0.08109608 22.628319    1.4657363   0.2945243  -0.08109608]
 [18.27084     1.4657363   0.2617994  -0.0810960

None
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([216], dtype=uint32), 'frameNumber': array([23250], dtype=uint32), 'numTLVs': array([2], dtype=uint16)}
NUMBER OF POINTS  5
[[ 1.4657363   0.45814893  0.08109608 15.523653    1.4657363 ]
 [ 0.425424    0.08109608 17.382263    1.5145941   0.425424  ]
 [ 0.08109608 25.146013    1.5145941   0.3926991   0.08109608]
 [31.524704    1.5145941   0.35997415 -0.08109608 20.099092  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([293], dtype=uint32), 'frameNumber': array([23251], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  9
[[ 1.4657363   0.45814893 -0.08109608 31.543709    1.4657363   0.425424
  -0.08109608 40.420395    1.5145941 ]
 [ 0.425424    0.08109608 42.17636     1.4657363   0.3926991  -0.08109608
  23.43539     1.5145941   0.3926991 ]
 [ 0.08109608 51.422615    1.5145941   0.35997415 -0.08109608 37.70394
   1.3191626   0.22907446  0.0810

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([168], dtype=uint32), 'frameNumber': array([23262], dtype=uint32), 'numTLVs': array([2], dtype=uint16)}
NUMBER OF POINTS  2
[[ 1.3680205   0.2945243 ]
 [-0.08109608 11.151882  ]
 [ 1.3680205   0.2617994 ]
 [-0.08109608 13.191523  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([178], dtype=uint32), 'frameNumber': array([23263], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  2
[[ 1.3680205   0.2945243 ]
 [-0.08109608 10.426439  ]
 [ 1.3680205   0.2617994 ]
 [-0.08109608 10.64844   ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([162], dtype=uint32), 'frameNumber': array([23264], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  1
[[ 1.4657363 ]
 [ 0.35997415]
 [ 0.08109608]
 [11.450841  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([137], dtype=uint

{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([180], dtype=uint32), 'frameNumber': array([23296], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  2
[[ 1.563452    0.425424  ]
 [-0.08109608 10.887495  ]
 [ 1.563452    0.3926991 ]
 [-0.08109608 10.950056  ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([162], dtype=uint32), 'frameNumber': array([23297], dtype=uint32), 'numTLVs': array([3], dtype=uint16)}
NUMBER OF POINTS  1
[[ 1.4657363 ]
 [ 0.35997415]
 [-0.08109608]
 [12.6243105 ]]
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([137], dtype=uint32), 'frameNumber': array([23298], dtype=uint32), 'numTLVs': array([2], dtype=uint16)}
None
{'magicBytes': array([2, 1, 4, 3, 6, 5, 8, 7], dtype=uint8), 'packetLength': array([128], dtype=uint32), 'frameNumber': array([23299], dtype=uint32), 'numTLVs': array([1], dtype=uint16)}
None
{'magicBytes': array([2, 1, 4, 3

In [40]:
print(pointCloud)

None


In [32]:
A = np.array([1,2,3])
B = np.reshape(A,(3,1))
            

In [98]:
x = np.array([89,153,34,63], dtype=np.uint8)
print(x.view(dtype=np.single))

[0.6351524]
